// vivibus timetable data — derived from ../vivibus/src/data/timetable.ts
window.VIVIBUS_STOPS_ORDERED = [
  {
    "id": "osatsu_st",
    "name": "長都駅東口"
  },
  {
    "id": "hokuyou_hs",
    "name": "北陽高校前"
  },
  {
    "id": "chitose_st",
    "name": "千歳駅前",
    "platforms": {
      "s1": "5番",
      "s2": "3番",
      "s3": "5番"
    }
  },
  {
    "id": "mori_moto",
    "name": "もりもと本店前"
  },
  {
    "id": "koizumi_clinic",
    "name": "古泉循環器内科クリニック前"
  },
  {
    "id": "city_hall",
    "name": "市役所前"
  },
  {
    "id": "asahi4",
    "name": "朝日町4丁目"
  },
  {
    "id": "asahi7",
    "name": "朝日町7丁目"
  },
  {
    "id": "office_arcadia",
    "name": "オフィス・アルカディア入口"
  },
  {
    "id": "minami_chitose",
    "name": "南千歳駅"
  },
  {
    "id": "air_cargo",
    "name": "エアカーゴ前"
  },
  {
    "id": "airport_dom28",
    "name": "新千歳空港国内線28番"
  },
  {
    "id": "airport_dom1",
    "name": "新千歳空港国内線1番"
  },
  {
    "id": "airport_intl",
    "name": "新千歳空港国際線85番"
  },
  {
    "id": "univ_research",
    "name": "科技大研究棟"
  },
  {
    "id": "univ_main",
    "name": "科技大本部棟"
  },
  {
    "id": "rapidas",
    "name": "ラピダス前"
  }
];
window.VIVIBUS_TRIPS = [
  {
    "id": "s2-w-to-001",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "times": {
      "chitose_st": "07:14",
      "mori_moto": "07:17",
      "koizumi_clinic": "07:18",
      "city_hall": "07:19",
      "asahi4": "07:20",
      "asahi7": "07:21",
      "office_arcadia": "07:25",
      "univ_research": "07:32",
      "univ_main": "07:35",
      "rapidas": "07:38"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-002",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "sogo",
    "times": {
      "chitose_st": "07:29",
      "mori_moto": "07:32",
      "koizumi_clinic": "07:33",
      "city_hall": "07:34",
      "asahi4": "07:35",
      "asahi7": "07:36",
      "office_arcadia": "07:40",
      "univ_research": "07:47",
      "univ_main": "07:50",
      "rapidas": "07:53"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-003",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "times": {
      "chitose_st": "08:04",
      "mori_moto": "08:07",
      "koizumi_clinic": "08:08",
      "city_hall": "08:09",
      "asahi4": "08:10",
      "asahi7": "08:11",
      "office_arcadia": "08:15",
      "univ_research": "08:22",
      "univ_main": "08:25",
      "rapidas": "08:28"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-004",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "times": {
      "chitose_st": "08:14",
      "mori_moto": "08:17",
      "koizumi_clinic": "08:18",
      "city_hall": "08:19",
      "asahi4": "08:20",
      "asahi7": "08:21",
      "office_arcadia": "08:25",
      "univ_research": "08:32",
      "univ_main": "08:35",
      "rapidas": "08:38"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-005",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "wing",
    "times": {
      "chitose_st": "08:19",
      "mori_moto": "08:22",
      "koizumi_clinic": "08:23",
      "city_hall": "08:24",
      "asahi4": "08:25",
      "asahi7": "08:26",
      "office_arcadia": "08:30",
      "univ_research": "08:37",
      "univ_main": "08:40",
      "rapidas": "08:43"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-006",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "sogo",
    "times": {
      "chitose_st": "08:24",
      "mori_moto": "08:27",
      "koizumi_clinic": "08:28",
      "city_hall": "08:29",
      "asahi4": "08:30",
      "asahi7": "08:31",
      "office_arcadia": "08:35",
      "univ_research": "08:42",
      "univ_main": "08:45",
      "rapidas": "08:48"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-007",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "donan",
    "times": {
      "chitose_st": "08:29",
      "mori_moto": "08:32",
      "koizumi_clinic": "08:33",
      "city_hall": "08:34",
      "asahi4": "08:35",
      "asahi7": "08:36",
      "office_arcadia": "08:40",
      "univ_research": "08:47",
      "univ_main": "08:50",
      "rapidas": "08:53"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-008",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "times": {
      "chitose_st": "09:04",
      "mori_moto": "09:07",
      "koizumi_clinic": "09:08",
      "city_hall": "09:09",
      "asahi4": "09:10",
      "asahi7": "09:11",
      "office_arcadia": "09:15",
      "univ_research": "09:22",
      "univ_main": "09:25",
      "rapidas": "09:28"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-009",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "wing",
    "times": {
      "chitose_st": "09:19",
      "mori_moto": "09:22",
      "koizumi_clinic": "09:23",
      "city_hall": "09:24",
      "asahi4": "09:25",
      "asahi7": "09:26",
      "office_arcadia": "09:30",
      "univ_research": "09:37",
      "univ_main": "09:40",
      "rapidas": "09:43"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-010",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "times": {
      "chitose_st": "09:34",
      "mori_moto": "09:37",
      "koizumi_clinic": "09:38",
      "city_hall": "09:39",
      "asahi4": "09:40",
      "asahi7": "09:41",
      "office_arcadia": "09:45",
      "univ_research": "09:52",
      "univ_main": "09:55",
      "rapidas": "09:58"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-011",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "sogo",
    "times": {
      "chitose_st": "09:44",
      "mori_moto": "09:47",
      "koizumi_clinic": "09:48",
      "city_hall": "09:49",
      "asahi4": "09:50",
      "asahi7": "09:51",
      "office_arcadia": "09:55",
      "univ_research": "10:02",
      "univ_main": "10:05",
      "rapidas": "10:08"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-012",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "donan",
    "times": {
      "chitose_st": "09:54",
      "mori_moto": "09:57",
      "koizumi_clinic": "09:58",
      "city_hall": "09:59",
      "asahi4": "10:00",
      "asahi7": "10:01",
      "office_arcadia": "10:05",
      "univ_research": "10:12",
      "univ_main": "10:15",
      "rapidas": "10:18"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-013",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "sogo",
    "times": {
      "chitose_st": "10:04",
      "mori_moto": "10:07",
      "koizumi_clinic": "10:08",
      "city_hall": "10:09",
      "asahi4": "10:10",
      "asahi7": "10:11",
      "office_arcadia": "10:15",
      "univ_research": "10:22",
      "univ_main": "10:25",
      "rapidas": "10:28"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-014",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "wing",
    "times": {
      "chitose_st": "10:14",
      "mori_moto": "10:17",
      "koizumi_clinic": "10:18",
      "city_hall": "10:19",
      "asahi4": "10:20",
      "asahi7": "10:21",
      "office_arcadia": "10:25",
      "univ_research": "10:32",
      "univ_main": "10:35",
      "rapidas": "10:38"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-015",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "sogo",
    "times": {
      "chitose_st": "14:24",
      "mori_moto": "14:27",
      "koizumi_clinic": "14:28",
      "city_hall": "14:29",
      "asahi4": "14:30",
      "asahi7": "14:31",
      "office_arcadia": "14:35",
      "univ_research": "14:42",
      "univ_main": "14:45",
      "rapidas": "14:48"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-016",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "times": {
      "chitose_st": "15:22",
      "mori_moto": "15:25",
      "koizumi_clinic": "15:26",
      "city_hall": "15:27",
      "asahi4": "15:28",
      "asahi7": "15:29",
      "office_arcadia": "15:33",
      "univ_research": "15:40",
      "univ_main": "15:43",
      "rapidas": "15:46"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-017",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "times": {
      "chitose_st": "15:55",
      "mori_moto": "15:58",
      "koizumi_clinic": "15:59",
      "city_hall": "16:00",
      "asahi4": "16:01",
      "asahi7": "16:02",
      "office_arcadia": "16:06",
      "univ_research": "16:13",
      "univ_main": "16:16",
      "rapidas": "16:19"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-018",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "sogo",
    "times": {
      "chitose_st": "16:04",
      "mori_moto": "16:07",
      "koizumi_clinic": "16:08",
      "city_hall": "16:09",
      "asahi4": "16:10",
      "asahi7": "16:11",
      "office_arcadia": "16:15",
      "univ_research": "16:22",
      "univ_main": "16:25",
      "rapidas": "16:28"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-to-019",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "sogo",
    "times": {
      "chitose_st": "17:51",
      "mori_moto": "17:54",
      "koizumi_clinic": "17:55",
      "city_hall": "17:56",
      "asahi4": "17:57",
      "asahi7": "17:58",
      "office_arcadia": "18:02",
      "univ_research": "18:09",
      "univ_main": "18:12",
      "rapidas": "18:15"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-w-to-0720",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "times": {
      "chitose_st": "07:20",
      "mori_moto": "07:23",
      "koizumi_clinic": "07:24",
      "city_hall": "07:25",
      "asahi4": "07:26",
      "asahi7": "07:27",
      "minami_chitose": "07:31",
      "air_cargo": "07:32",
      "airport_dom28": "07:33",
      "airport_dom1": "07:34",
      "airport_intl": "07:37",
      "univ_research": "07:44",
      "univ_main": "07:45",
      "rapidas": "07:48"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-h-to-0720",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "sogo",
    "times": {
      "chitose_st": "07:20",
      "mori_moto": "07:23",
      "koizumi_clinic": "07:24",
      "city_hall": "07:25",
      "asahi4": "07:26",
      "asahi7": "07:27",
      "minami_chitose": "07:31",
      "air_cargo": "07:32",
      "airport_dom28": "07:33",
      "airport_dom1": "07:34",
      "airport_intl": "07:37",
      "univ_research": "07:44",
      "univ_main": "07:45",
      "rapidas": "07:48"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-hd-to-001",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "sogo",
    "times": {
      "chitose_st": "08:18",
      "mori_moto": "08:21",
      "koizumi_clinic": "08:22",
      "city_hall": "08:23",
      "asahi4": "08:24",
      "asahi7": "08:25",
      "minami_chitose": "08:29",
      "air_cargo": "08:30",
      "airport_dom28": "08:31",
      "airport_dom1": "08:32",
      "airport_intl": "08:35",
      "univ_research": "08:42",
      "univ_main": "08:43",
      "rapidas": "08:46"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-hd-to-002",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "sogo",
    "times": {
      "chitose_st": "09:10",
      "mori_moto": "09:13",
      "koizumi_clinic": "09:14",
      "city_hall": "09:15",
      "asahi4": "09:16",
      "asahi7": "09:17",
      "minami_chitose": "09:21",
      "air_cargo": "09:22",
      "airport_dom28": "09:23",
      "airport_dom1": "09:24",
      "airport_intl": "09:27",
      "univ_research": "09:34",
      "univ_main": "09:35",
      "rapidas": "09:38"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-w-to-001",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "times": {
      "chitose_st": "10:30",
      "mori_moto": "10:33",
      "koizumi_clinic": "10:34",
      "city_hall": "10:35",
      "asahi4": "10:36",
      "asahi7": "10:37",
      "minami_chitose": "10:41",
      "air_cargo": "10:42",
      "airport_dom28": "10:43",
      "airport_dom1": "10:44",
      "airport_intl": "10:47",
      "univ_research": "10:54",
      "univ_main": "10:55",
      "rapidas": "10:58"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-w-to-002",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "wing",
    "times": {
      "chitose_st": "11:00",
      "mori_moto": "11:03",
      "koizumi_clinic": "11:04",
      "city_hall": "11:05",
      "asahi4": "11:06",
      "asahi7": "11:07",
      "minami_chitose": "11:11",
      "air_cargo": "11:12",
      "airport_dom28": "11:13",
      "airport_dom1": "11:14",
      "airport_intl": "11:17",
      "univ_research": "11:24",
      "univ_main": "11:25",
      "rapidas": "11:28"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-w-to-003",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "times": {
      "chitose_st": "12:10",
      "mori_moto": "12:13",
      "koizumi_clinic": "12:14",
      "city_hall": "12:15",
      "asahi4": "12:16",
      "asahi7": "12:17",
      "minami_chitose": "12:21",
      "air_cargo": "12:22",
      "airport_dom28": "12:23",
      "airport_dom1": "12:24",
      "airport_intl": "12:27",
      "univ_research": "12:34",
      "univ_main": "12:35",
      "rapidas": "12:38"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-ed-to-002",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "everyday",
    "via": "airport",
    "company": "sogo",
    "times": {
      "chitose_st": "13:20",
      "mori_moto": "13:23",
      "koizumi_clinic": "13:24",
      "city_hall": "13:25",
      "asahi4": "13:26",
      "asahi7": "13:27",
      "minami_chitose": "13:31",
      "air_cargo": "13:32",
      "airport_dom28": "13:33",
      "airport_dom1": "13:34",
      "airport_intl": "13:37",
      "univ_research": "13:44",
      "univ_main": "13:45",
      "rapidas": "13:48"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s3-ed-to-001-w",
    "route": "s3",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "osatsu",
    "company": "hokuto",
    "times": {
      "osatsu_st": "11:10",
      "hokuyou_hs": "11:16",
      "chitose_st": "11:29",
      "mori_moto": "11:32",
      "koizumi_clinic": "11:33",
      "city_hall": "11:34",
      "asahi4": "11:35",
      "asahi7": "11:36",
      "minami_chitose": "11:40",
      "air_cargo": "11:41",
      "airport_dom28": "11:42",
      "airport_dom1": "11:43",
      "airport_intl": "11:46",
      "univ_research": "11:53",
      "univ_main": "11:54",
      "rapidas": "12:02"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s3-ed-to-001-h",
    "route": "s3",
    "direction": "to_univ",
    "serviceDay": "holiday_only",
    "via": "osatsu",
    "company": "sogo",
    "times": {
      "osatsu_st": "11:10",
      "hokuyou_hs": "11:16",
      "chitose_st": "11:29",
      "mori_moto": "11:32",
      "koizumi_clinic": "11:33",
      "city_hall": "11:34",
      "asahi4": "11:35",
      "asahi7": "11:36",
      "minami_chitose": "11:40",
      "air_cargo": "11:41",
      "airport_dom28": "11:42",
      "airport_dom1": "11:43",
      "airport_intl": "11:46",
      "univ_research": "11:53",
      "univ_main": "11:54",
      "rapidas": "12:02"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s3-w-to-001",
    "route": "s3",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "osatsu",
    "company": "sogo",
    "times": {
      "osatsu_st": "12:00",
      "hokuyou_hs": "12:06",
      "chitose_st": "12:19",
      "mori_moto": "12:22",
      "koizumi_clinic": "12:23",
      "city_hall": "12:24",
      "asahi4": "12:25",
      "asahi7": "12:26",
      "minami_chitose": "12:30",
      "air_cargo": "12:31",
      "airport_dom28": "12:32",
      "airport_dom1": "12:33",
      "airport_intl": "12:36",
      "univ_research": "12:43",
      "univ_main": "12:44",
      "rapidas": "12:52"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s3-w-to-002",
    "route": "s3",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "osatsu",
    "company": "sogo",
    "times": {
      "osatsu_st": "14:10",
      "hokuyou_hs": "14:16",
      "chitose_st": "14:29",
      "mori_moto": "14:32",
      "koizumi_clinic": "14:33",
      "city_hall": "14:34",
      "asahi4": "14:35",
      "asahi7": "14:36",
      "minami_chitose": "14:40",
      "air_cargo": "14:41",
      "airport_dom28": "14:42",
      "airport_dom1": "14:43",
      "airport_intl": "14:46",
      "univ_research": "14:53",
      "univ_main": "14:54",
      "rapidas": "15:02"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-fr-001",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "sogo",
    "times": {
      "rapidas": "11:00",
      "univ_main": "11:02",
      "univ_research": "11:05",
      "office_arcadia": "11:12",
      "asahi7": "11:16",
      "asahi4": "11:17",
      "city_hall": "11:18",
      "koizumi_clinic": "11:19",
      "mori_moto": "11:20",
      "chitose_st": "11:24"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-fr-002",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "times": {
      "rapidas": "12:25",
      "univ_main": "12:27",
      "univ_research": "12:30",
      "office_arcadia": "12:37",
      "asahi7": "12:41",
      "asahi4": "12:42",
      "city_hall": "12:43",
      "koizumi_clinic": "12:44",
      "mori_moto": "12:45",
      "chitose_st": "12:49"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-fr-003",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "times": {
      "rapidas": "13:05",
      "univ_main": "13:07",
      "univ_research": "13:10",
      "office_arcadia": "13:17",
      "asahi7": "13:21",
      "asahi4": "13:22",
      "city_hall": "13:23",
      "koizumi_clinic": "13:24",
      "mori_moto": "13:25",
      "chitose_st": "13:29"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-fr-004",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "times": {
      "rapidas": "14:15",
      "univ_main": "14:17",
      "univ_research": "14:20",
      "office_arcadia": "14:27",
      "asahi7": "14:31",
      "asahi4": "14:32",
      "city_hall": "14:33",
      "koizumi_clinic": "14:34",
      "mori_moto": "14:35",
      "chitose_st": "14:39"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-fr-005",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "wing",
    "times": {
      "rapidas": "15:00",
      "univ_main": "15:02",
      "univ_research": "15:05",
      "office_arcadia": "15:12",
      "asahi7": "15:16",
      "asahi4": "15:17",
      "city_hall": "15:18",
      "koizumi_clinic": "15:19",
      "mori_moto": "15:20",
      "chitose_st": "15:24"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-fr-006",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "sogo",
    "times": {
      "rapidas": "16:40",
      "univ_main": "16:42",
      "univ_research": "16:45",
      "office_arcadia": "16:52",
      "asahi7": "16:56",
      "asahi4": "16:57",
      "city_hall": "16:58",
      "koizumi_clinic": "16:59",
      "mori_moto": "17:00",
      "chitose_st": "17:04"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-fr-007",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "sogo",
    "times": {
      "rapidas": "17:00",
      "univ_main": "17:02",
      "univ_research": "17:05",
      "office_arcadia": "17:12",
      "asahi7": "17:16",
      "asahi4": "17:17",
      "city_hall": "17:18",
      "koizumi_clinic": "17:19",
      "mori_moto": "17:20",
      "chitose_st": "17:24"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-fr-008",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "times": {
      "rapidas": "17:28",
      "univ_main": "17:30",
      "univ_research": "17:33",
      "office_arcadia": "17:40",
      "asahi7": "17:44",
      "asahi4": "17:45",
      "city_hall": "17:46",
      "koizumi_clinic": "17:47",
      "mori_moto": "17:48",
      "chitose_st": "17:52"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-w-fr-009",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "everyday",
    "via": "direct",
    "company": "sogo",
    "times": {
      "rapidas": "18:25",
      "univ_main": "18:27",
      "univ_research": "18:30",
      "office_arcadia": "18:37",
      "asahi7": "18:41",
      "asahi4": "18:42",
      "city_hall": "18:43",
      "koizumi_clinic": "18:44",
      "mori_moto": "18:45",
      "chitose_st": "18:49"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-w-fr-001",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "sogo",
    "times": {
      "rapidas": "11:34",
      "univ_main": "11:36",
      "univ_research": "11:39",
      "airport_dom28": "11:46",
      "airport_dom1": "11:47",
      "airport_intl": "11:48",
      "air_cargo": "11:50",
      "minami_chitose": "11:51",
      "asahi7": "11:54",
      "asahi4": "11:55",
      "city_hall": "11:56",
      "koizumi_clinic": "11:57",
      "mori_moto": "11:58",
      "chitose_st": "12:02"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-hd-fr-001b",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "sogo",
    "times": {
      "rapidas": "12:40",
      "univ_main": "12:42",
      "univ_research": "12:45",
      "airport_dom28": "12:52",
      "airport_dom1": "12:53",
      "airport_intl": "12:54",
      "air_cargo": "12:56",
      "minami_chitose": "12:57",
      "asahi7": "13:00",
      "asahi4": "13:01",
      "city_hall": "13:02",
      "koizumi_clinic": "13:03",
      "mori_moto": "13:04",
      "chitose_st": "13:08"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-w-fr-002",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "times": {
      "rapidas": "13:33",
      "univ_main": "13:35",
      "univ_research": "13:38",
      "airport_dom28": "13:45",
      "airport_dom1": "13:46",
      "airport_intl": "13:47",
      "air_cargo": "13:49",
      "minami_chitose": "13:50",
      "asahi7": "13:53",
      "asahi4": "13:54",
      "city_hall": "13:55",
      "koizumi_clinic": "13:56",
      "mori_moto": "13:57",
      "chitose_st": "14:01"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-hd-fr-001",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "sogo",
    "times": {
      "rapidas": "14:30",
      "univ_main": "14:32",
      "univ_research": "14:35",
      "airport_dom28": "14:42",
      "airport_dom1": "14:43",
      "airport_intl": "14:44",
      "air_cargo": "14:46",
      "minami_chitose": "14:47",
      "asahi7": "14:50",
      "asahi4": "14:51",
      "city_hall": "14:52",
      "koizumi_clinic": "14:53",
      "mori_moto": "14:54",
      "chitose_st": "14:58"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-ed-fr-002-sogo",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "sogo",
    "times": {
      "rapidas": "15:22",
      "univ_main": "15:24",
      "univ_research": "15:27",
      "airport_dom28": "15:34",
      "airport_dom1": "15:35",
      "airport_intl": "15:36",
      "air_cargo": "15:38",
      "minami_chitose": "15:39",
      "asahi7": "15:42",
      "asahi4": "15:43",
      "city_hall": "15:44",
      "koizumi_clinic": "15:45",
      "mori_moto": "15:46",
      "chitose_st": "15:50"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-ed-fr-002-hokuto",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "hokuto",
    "times": {
      "rapidas": "15:22",
      "univ_main": "15:24",
      "univ_research": "15:27",
      "airport_dom28": "15:34",
      "airport_dom1": "15:35",
      "airport_intl": "15:36",
      "air_cargo": "15:38",
      "minami_chitose": "15:39",
      "asahi7": "15:42",
      "asahi4": "15:43",
      "city_hall": "15:44",
      "koizumi_clinic": "15:45",
      "mori_moto": "15:46",
      "chitose_st": "15:50"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-ed-fr-003b-h",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "hokuto",
    "times": {
      "rapidas": "16:45",
      "univ_main": "16:47",
      "univ_research": "16:50",
      "airport_dom28": "16:57",
      "airport_dom1": "16:58",
      "airport_intl": "16:59",
      "air_cargo": "17:01",
      "minami_chitose": "17:02",
      "asahi7": "17:05",
      "asahi4": "17:06",
      "city_hall": "17:07",
      "koizumi_clinic": "17:08",
      "mori_moto": "17:09",
      "chitose_st": "17:13"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-ed-fr-003b-w",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "wing",
    "times": {
      "rapidas": "16:45",
      "univ_main": "16:47",
      "univ_research": "16:50",
      "airport_dom28": "16:57",
      "airport_dom1": "16:58",
      "airport_intl": "16:59",
      "air_cargo": "17:01",
      "minami_chitose": "17:02",
      "asahi7": "17:05",
      "asahi4": "17:06",
      "city_hall": "17:07",
      "koizumi_clinic": "17:08",
      "mori_moto": "17:09",
      "chitose_st": "17:13"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-ed-fr-003",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "everyday",
    "via": "airport",
    "company": "hokuto",
    "times": {
      "rapidas": "17:50",
      "univ_main": "17:52",
      "univ_research": "17:55",
      "airport_dom28": "18:02",
      "airport_dom1": "18:03",
      "airport_intl": "18:04",
      "air_cargo": "18:06",
      "minami_chitose": "18:07",
      "asahi7": "18:10",
      "asahi4": "18:11",
      "city_hall": "18:12",
      "koizumi_clinic": "18:13",
      "mori_moto": "18:14",
      "chitose_st": "18:18"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-ed-fr-004",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "everyday",
    "via": "airport",
    "company": "hokuto",
    "times": {
      "rapidas": "19:00",
      "univ_main": "19:02",
      "univ_research": "19:05",
      "airport_dom28": "19:12",
      "airport_dom1": "19:13",
      "airport_intl": "19:14",
      "air_cargo": "19:16",
      "minami_chitose": "19:17",
      "asahi7": "19:20",
      "asahi4": "19:21",
      "city_hall": "19:22",
      "koizumi_clinic": "19:23",
      "mori_moto": "19:24",
      "chitose_st": "19:28"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-w-fr-005",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "times": {
      "rapidas": "19:40",
      "univ_main": "19:42",
      "univ_research": "19:45",
      "airport_dom28": "19:52",
      "airport_dom1": "19:53",
      "airport_intl": "19:54",
      "air_cargo": "19:56",
      "minami_chitose": "19:57",
      "asahi7": "20:00",
      "asahi4": "20:01",
      "city_hall": "20:02",
      "koizumi_clinic": "20:03",
      "mori_moto": "20:04",
      "chitose_st": "20:08"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s1-w-fr-006",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "times": {
      "rapidas": "21:20",
      "univ_main": "21:22",
      "univ_research": "21:25",
      "airport_dom28": "21:32",
      "airport_dom1": "21:33",
      "airport_intl": "21:34",
      "air_cargo": "21:36",
      "minami_chitose": "21:37",
      "asahi7": "21:40",
      "asahi4": "21:41",
      "city_hall": "21:42",
      "koizumi_clinic": "21:43",
      "mori_moto": "21:44",
      "chitose_st": "21:48"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s3-ed-fr-001",
    "route": "s3",
    "direction": "to_city",
    "serviceDay": "everyday",
    "via": "osatsu",
    "company": "hokuto",
    "times": {
      "rapidas": "20:30",
      "univ_main": "20:32",
      "univ_research": "20:35",
      "airport_dom28": "20:42",
      "airport_dom1": "20:43",
      "airport_intl": "20:44",
      "air_cargo": "20:46",
      "minami_chitose": "20:47",
      "asahi7": "20:50",
      "asahi4": "20:51",
      "city_hall": "20:52",
      "koizumi_clinic": "20:53",
      "mori_moto": "20:54",
      "chitose_st": "21:00",
      "hokuyou_hs": "21:08",
      "osatsu_st": "21:22"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s3-ed-fr-002",
    "route": "s3",
    "direction": "to_city",
    "serviceDay": "everyday",
    "via": "osatsu",
    "company": "hokuto",
    "times": {
      "rapidas": "22:00",
      "univ_main": "22:02",
      "univ_research": "22:05",
      "airport_dom28": "22:12",
      "airport_dom1": "22:13",
      "airport_intl": "22:14",
      "air_cargo": "22:16",
      "minami_chitose": "22:17",
      "asahi7": "22:20",
      "asahi4": "22:21",
      "city_hall": "22:22",
      "koizumi_clinic": "22:23",
      "mori_moto": "22:24",
      "chitose_st": "22:30",
      "hokuyou_hs": "22:38",
      "osatsu_st": "22:52"
    },
    "schoolHolidayBehavior": "suspended"
  },
  {
    "id": "s2-holiday-to-0810",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "wing",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "08:10",
      "mori_moto": "08:13",
      "koizumi_clinic": "08:14",
      "city_hall": "08:15",
      "asahi4": "08:16",
      "asahi7": "08:17",
      "office_arcadia": "08:21",
      "univ_research": "08:28",
      "univ_main": "08:31",
      "rapidas": "08:34"
    }
  },
  {
    "id": "s2-holiday-to-0840",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "donan",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "08:40",
      "mori_moto": "08:43",
      "koizumi_clinic": "08:44",
      "city_hall": "08:45",
      "asahi4": "08:46",
      "asahi7": "08:47",
      "office_arcadia": "08:51",
      "univ_research": "08:58",
      "univ_main": "09:01",
      "rapidas": "09:04"
    }
  },
  {
    "id": "s2-holiday-to-0910",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "wing",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "09:10",
      "mori_moto": "09:13",
      "koizumi_clinic": "09:14",
      "city_hall": "09:15",
      "asahi4": "09:16",
      "asahi7": "09:17",
      "office_arcadia": "09:21",
      "univ_research": "09:28",
      "univ_main": "09:31",
      "rapidas": "09:34"
    }
  },
  {
    "id": "s2-holiday-to-0950",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "donan",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "09:50",
      "mori_moto": "09:53",
      "koizumi_clinic": "09:54",
      "city_hall": "09:55",
      "asahi4": "09:56",
      "asahi7": "09:57",
      "office_arcadia": "10:01",
      "univ_research": "10:08",
      "univ_main": "10:11",
      "rapidas": "10:14"
    }
  },
  {
    "id": "s2-holiday-to-1600",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "16:00",
      "mori_moto": "16:03",
      "koizumi_clinic": "16:04",
      "city_hall": "16:05",
      "asahi4": "16:06",
      "asahi7": "16:07",
      "office_arcadia": "16:11",
      "univ_research": "16:18",
      "univ_main": "16:21",
      "rapidas": "16:24"
    }
  },
  {
    "id": "s2-holiday-to-1800",
    "route": "s2",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "18:00",
      "mori_moto": "18:03",
      "koizumi_clinic": "18:04",
      "city_hall": "18:05",
      "asahi4": "18:06",
      "asahi7": "18:07",
      "office_arcadia": "18:11",
      "univ_research": "18:18",
      "univ_main": "18:21",
      "rapidas": "18:24"
    }
  },
  {
    "id": "s1-holiday-to-0720-w",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "07:20",
      "mori_moto": "07:23",
      "koizumi_clinic": "07:24",
      "city_hall": "07:25",
      "asahi4": "07:26",
      "asahi7": "07:27",
      "minami_chitose": "07:31",
      "air_cargo": "07:32",
      "airport_dom28": "07:33",
      "airport_dom1": "07:34",
      "airport_intl": "07:37",
      "univ_research": "07:44",
      "univ_main": "07:45",
      "rapidas": "07:48"
    }
  },
  {
    "id": "s1-holiday-to-0720-h",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "07:20",
      "mori_moto": "07:23",
      "koizumi_clinic": "07:24",
      "city_hall": "07:25",
      "asahi4": "07:26",
      "asahi7": "07:27",
      "minami_chitose": "07:31",
      "air_cargo": "07:32",
      "airport_dom28": "07:33",
      "airport_dom1": "07:34",
      "airport_intl": "07:37",
      "univ_research": "07:44",
      "univ_main": "07:45",
      "rapidas": "07:48"
    }
  },
  {
    "id": "s1-holiday-to-0810-h",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "08:10",
      "mori_moto": "08:13",
      "koizumi_clinic": "08:14",
      "city_hall": "08:15",
      "asahi4": "08:16",
      "asahi7": "08:17",
      "minami_chitose": "08:21",
      "air_cargo": "08:22",
      "airport_dom28": "08:23",
      "airport_dom1": "08:24",
      "airport_intl": "08:27",
      "univ_research": "08:34",
      "univ_main": "08:35",
      "rapidas": "08:38"
    }
  },
  {
    "id": "s1-holiday-to-0910-h",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "09:10",
      "mori_moto": "09:13",
      "koizumi_clinic": "09:14",
      "city_hall": "09:15",
      "asahi4": "09:16",
      "asahi7": "09:17",
      "minami_chitose": "09:21",
      "air_cargo": "09:22",
      "airport_dom28": "09:23",
      "airport_dom1": "09:24",
      "airport_intl": "09:27",
      "univ_research": "09:34",
      "univ_main": "09:35",
      "rapidas": "09:38"
    }
  },
  {
    "id": "s1-holiday-to-1030-w",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "wing",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "10:30",
      "mori_moto": "10:33",
      "koizumi_clinic": "10:34",
      "city_hall": "10:35",
      "asahi4": "10:36",
      "asahi7": "10:37",
      "minami_chitose": "10:41",
      "air_cargo": "10:42",
      "airport_dom28": "10:43",
      "airport_dom1": "10:44",
      "airport_intl": "10:47",
      "univ_research": "10:54",
      "univ_main": "10:55",
      "rapidas": "10:58"
    }
  },
  {
    "id": "s1-holiday-to-1100-w",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "11:00",
      "mori_moto": "11:03",
      "koizumi_clinic": "11:04",
      "city_hall": "11:05",
      "asahi4": "11:06",
      "asahi7": "11:07",
      "minami_chitose": "11:11",
      "air_cargo": "11:12",
      "airport_dom28": "11:13",
      "airport_dom1": "11:14",
      "airport_intl": "11:17",
      "univ_research": "11:24",
      "univ_main": "11:25",
      "rapidas": "11:28"
    }
  },
  {
    "id": "s1-holiday-to-1205-w",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "12:05",
      "mori_moto": "12:08",
      "koizumi_clinic": "12:09",
      "city_hall": "12:10",
      "asahi4": "12:11",
      "asahi7": "12:12",
      "minami_chitose": "12:16",
      "air_cargo": "12:17",
      "airport_dom28": "12:18",
      "airport_dom1": "12:19",
      "airport_intl": "12:22",
      "univ_research": "12:29",
      "univ_main": "12:30",
      "rapidas": "12:33"
    }
  },
  {
    "id": "s1-holiday-to-1320-w",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "13:20",
      "mori_moto": "13:23",
      "koizumi_clinic": "13:24",
      "city_hall": "13:25",
      "asahi4": "13:26",
      "asahi7": "13:27",
      "minami_chitose": "13:31",
      "air_cargo": "13:32",
      "airport_dom28": "13:33",
      "airport_dom1": "13:34",
      "airport_intl": "13:37",
      "univ_research": "13:44",
      "univ_main": "13:45",
      "rapidas": "13:48"
    }
  },
  {
    "id": "s1-holiday-to-1320-h",
    "route": "s1",
    "direction": "to_univ",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "chitose_st": "13:20",
      "mori_moto": "13:23",
      "koizumi_clinic": "13:24",
      "city_hall": "13:25",
      "asahi4": "13:26",
      "asahi7": "13:27",
      "minami_chitose": "13:31",
      "air_cargo": "13:32",
      "airport_dom28": "13:33",
      "airport_dom1": "13:34",
      "airport_intl": "13:37",
      "univ_research": "13:44",
      "univ_main": "13:45",
      "rapidas": "13:48"
    }
  },
  {
    "id": "s3-holiday-to-1129-w",
    "route": "s3",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "osatsu",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "osatsu_st": "11:10",
      "hokuyou_hs": "11:16",
      "chitose_st": "11:29",
      "mori_moto": "11:32",
      "koizumi_clinic": "11:33",
      "city_hall": "11:34",
      "asahi4": "11:35",
      "asahi7": "11:36",
      "minami_chitose": "11:40",
      "air_cargo": "11:41",
      "airport_dom28": "11:42",
      "airport_dom1": "11:43",
      "airport_intl": "11:46",
      "univ_research": "11:53",
      "univ_main": "11:54",
      "rapidas": "12:02"
    }
  },
  {
    "id": "s3-holiday-to-1129-h",
    "route": "s3",
    "direction": "to_univ",
    "serviceDay": "holiday_only",
    "via": "osatsu",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "osatsu_st": "11:10",
      "hokuyou_hs": "11:16",
      "chitose_st": "11:29",
      "mori_moto": "11:32",
      "koizumi_clinic": "11:33",
      "city_hall": "11:34",
      "asahi4": "11:35",
      "asahi7": "11:36",
      "minami_chitose": "11:40",
      "air_cargo": "11:41",
      "airport_dom28": "11:42",
      "airport_dom1": "11:43",
      "airport_intl": "11:46",
      "univ_research": "11:53",
      "univ_main": "11:54",
      "rapidas": "12:02"
    }
  },
  {
    "id": "s3-holiday-to-1229-w",
    "route": "s3",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "osatsu",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "osatsu_st": "12:10",
      "hokuyou_hs": "12:16",
      "chitose_st": "12:29",
      "mori_moto": "12:32",
      "koizumi_clinic": "12:33",
      "city_hall": "12:34",
      "asahi4": "12:35",
      "asahi7": "12:36",
      "minami_chitose": "12:40",
      "air_cargo": "12:41",
      "airport_dom28": "12:42",
      "airport_dom1": "12:43",
      "airport_intl": "12:46",
      "univ_research": "12:53",
      "univ_main": "12:54",
      "rapidas": "13:02"
    }
  },
  {
    "id": "s3-holiday-to-1429-w",
    "route": "s3",
    "direction": "to_univ",
    "serviceDay": "weekday",
    "via": "osatsu",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "osatsu_st": "14:10",
      "hokuyou_hs": "14:16",
      "chitose_st": "14:29",
      "mori_moto": "14:32",
      "koizumi_clinic": "14:33",
      "city_hall": "14:34",
      "asahi4": "14:35",
      "asahi7": "14:36",
      "minami_chitose": "14:40",
      "air_cargo": "14:41",
      "airport_dom28": "14:42",
      "airport_dom1": "14:43",
      "airport_intl": "14:46",
      "univ_research": "14:53",
      "univ_main": "14:54",
      "rapidas": "15:02"
    }
  },
  {
    "id": "s2-holiday-fr-1232",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "12:30",
      "univ_main": "12:32",
      "univ_research": "12:35",
      "office_arcadia": "12:42",
      "asahi7": "12:46",
      "asahi4": "12:47",
      "city_hall": "12:48",
      "koizumi_clinic": "12:49",
      "mori_moto": "12:50",
      "chitose_st": "12:54"
    }
  },
  {
    "id": "s2-holiday-fr-1432",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "wing",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "14:30",
      "univ_main": "14:32",
      "univ_research": "14:35",
      "office_arcadia": "14:42",
      "asahi7": "14:46",
      "asahi4": "14:47",
      "city_hall": "14:48",
      "koizumi_clinic": "14:49",
      "mori_moto": "14:50",
      "chitose_st": "14:54"
    }
  },
  {
    "id": "s2-holiday-fr-1732",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "17:30",
      "univ_main": "17:32",
      "univ_research": "17:35",
      "office_arcadia": "17:42",
      "asahi7": "17:46",
      "asahi4": "17:47",
      "city_hall": "17:48",
      "koizumi_clinic": "17:49",
      "mori_moto": "17:50",
      "chitose_st": "17:54"
    }
  },
  {
    "id": "s2-holiday-fr-1832",
    "route": "s2",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "direct",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "18:30",
      "univ_main": "18:32",
      "univ_research": "18:35",
      "office_arcadia": "18:42",
      "asahi7": "18:46",
      "asahi4": "18:47",
      "city_hall": "18:48",
      "koizumi_clinic": "18:49",
      "mori_moto": "18:50",
      "chitose_st": "18:54"
    }
  },
  {
    "id": "s1-holiday-fr-1136",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "11:34",
      "univ_main": "11:36",
      "univ_research": "11:39",
      "airport_dom28": "11:46",
      "airport_dom1": "11:47",
      "airport_intl": "11:48",
      "air_cargo": "11:50",
      "minami_chitose": "11:51",
      "asahi7": "11:54",
      "asahi4": "11:55",
      "city_hall": "11:56",
      "koizumi_clinic": "11:57",
      "mori_moto": "11:58",
      "chitose_st": "12:02"
    }
  },
  {
    "id": "s1-holiday-fr-1232",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "12:30",
      "univ_main": "12:32",
      "univ_research": "12:35",
      "airport_dom28": "12:42",
      "airport_dom1": "12:43",
      "airport_intl": "12:44",
      "air_cargo": "12:46",
      "minami_chitose": "12:47",
      "asahi7": "12:50",
      "asahi4": "12:51",
      "city_hall": "12:52",
      "koizumi_clinic": "12:53",
      "mori_moto": "12:54",
      "chitose_st": "12:58"
    }
  },
  {
    "id": "s1-holiday-fr-1335",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "13:33",
      "univ_main": "13:35",
      "univ_research": "13:38",
      "airport_dom28": "13:45",
      "airport_dom1": "13:46",
      "airport_intl": "13:47",
      "air_cargo": "13:49",
      "minami_chitose": "13:50",
      "asahi7": "13:53",
      "asahi4": "13:54",
      "city_hall": "13:55",
      "koizumi_clinic": "13:56",
      "mori_moto": "13:57",
      "chitose_st": "14:01"
    }
  },
  {
    "id": "s1-holiday-fr-1432",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "14:30",
      "univ_main": "14:32",
      "univ_research": "14:35",
      "airport_dom28": "14:42",
      "airport_dom1": "14:43",
      "airport_intl": "14:44",
      "air_cargo": "14:46",
      "minami_chitose": "14:47",
      "asahi7": "14:50",
      "asahi4": "14:51",
      "city_hall": "14:52",
      "koizumi_clinic": "14:53",
      "mori_moto": "14:54",
      "chitose_st": "14:58"
    }
  },
  {
    "id": "s1-holiday-fr-1524",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "everyday",
    "via": "airport",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "15:22",
      "univ_main": "15:24",
      "univ_research": "15:27",
      "airport_dom28": "15:34",
      "airport_dom1": "15:35",
      "airport_intl": "15:36",
      "air_cargo": "15:38",
      "minami_chitose": "15:39",
      "asahi7": "15:42",
      "asahi4": "15:43",
      "city_hall": "15:44",
      "koizumi_clinic": "15:45",
      "mori_moto": "15:46",
      "chitose_st": "15:50"
    }
  },
  {
    "id": "s1-holiday-fr-1647-w",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "sogo",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "16:45",
      "univ_main": "16:47",
      "univ_research": "16:50",
      "airport_dom28": "16:57",
      "airport_dom1": "16:58",
      "airport_intl": "16:59",
      "air_cargo": "17:01",
      "minami_chitose": "17:02",
      "asahi7": "17:05",
      "asahi4": "17:06",
      "city_hall": "17:07",
      "koizumi_clinic": "17:08",
      "mori_moto": "17:09",
      "chitose_st": "17:13"
    }
  },
  {
    "id": "s1-holiday-fr-1647-h",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "holiday_only",
    "via": "airport",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "16:45",
      "univ_main": "16:47",
      "univ_research": "16:50",
      "airport_dom28": "16:57",
      "airport_dom1": "16:58",
      "airport_intl": "16:59",
      "air_cargo": "17:01",
      "minami_chitose": "17:02",
      "asahi7": "17:05",
      "asahi4": "17:06",
      "city_hall": "17:07",
      "koizumi_clinic": "17:08",
      "mori_moto": "17:09",
      "chitose_st": "17:13"
    }
  },
  {
    "id": "s1-holiday-fr-1752",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "everyday",
    "via": "airport",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "17:50",
      "univ_main": "17:52",
      "univ_research": "17:55",
      "airport_dom28": "18:02",
      "airport_dom1": "18:03",
      "airport_intl": "18:04",
      "air_cargo": "18:06",
      "minami_chitose": "18:07",
      "asahi7": "18:10",
      "asahi4": "18:11",
      "city_hall": "18:12",
      "koizumi_clinic": "18:13",
      "mori_moto": "18:14",
      "chitose_st": "18:18"
    }
  },
  {
    "id": "s1-holiday-fr-1902",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "everyday",
    "via": "airport",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "19:00",
      "univ_main": "19:02",
      "univ_research": "19:05",
      "airport_dom28": "19:12",
      "airport_dom1": "19:13",
      "airport_intl": "19:14",
      "air_cargo": "19:16",
      "minami_chitose": "19:17",
      "asahi7": "19:20",
      "asahi4": "19:21",
      "city_hall": "19:22",
      "koizumi_clinic": "19:23",
      "mori_moto": "19:24",
      "chitose_st": "19:28"
    }
  },
  {
    "id": "s1-holiday-fr-1942",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "19:40",
      "univ_main": "19:42",
      "univ_research": "19:45",
      "airport_dom28": "19:52",
      "airport_dom1": "19:53",
      "airport_intl": "19:54",
      "air_cargo": "19:56",
      "minami_chitose": "19:57",
      "asahi7": "20:00",
      "asahi4": "20:01",
      "city_hall": "20:02",
      "koizumi_clinic": "20:03",
      "mori_moto": "20:04",
      "chitose_st": "20:08"
    }
  },
  {
    "id": "s1-holiday-fr-2122",
    "route": "s1",
    "direction": "to_city",
    "serviceDay": "weekday",
    "via": "airport",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "21:20",
      "univ_main": "21:22",
      "univ_research": "21:25",
      "airport_dom28": "21:32",
      "airport_dom1": "21:33",
      "airport_intl": "21:34",
      "air_cargo": "21:36",
      "minami_chitose": "21:37",
      "asahi7": "21:40",
      "asahi4": "21:41",
      "city_hall": "21:42",
      "koizumi_clinic": "21:43",
      "mori_moto": "21:44",
      "chitose_st": "21:48"
    }
  },
  {
    "id": "s3-holiday-fr-2032",
    "route": "s3",
    "direction": "to_city",
    "serviceDay": "everyday",
    "via": "osatsu",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "20:30",
      "univ_main": "20:32",
      "univ_research": "20:35",
      "airport_dom28": "20:42",
      "airport_dom1": "20:43",
      "airport_intl": "20:44",
      "air_cargo": "20:46",
      "minami_chitose": "20:47",
      "asahi7": "20:50",
      "asahi4": "20:51",
      "city_hall": "20:52",
      "koizumi_clinic": "20:53",
      "mori_moto": "20:54",
      "chitose_st": "21:00",
      "hokuyou_hs": "21:08",
      "osatsu_st": "21:22"
    }
  },
  {
    "id": "s3-holiday-fr-2202",
    "route": "s3",
    "direction": "to_city",
    "serviceDay": "everyday",
    "via": "osatsu",
    "company": "hokuto",
    "schoolHolidayBehavior": "holiday_only",
    "times": {
      "rapidas": "22:00",
      "univ_main": "22:02",
      "univ_research": "22:05",
      "airport_dom28": "22:12",
      "airport_dom1": "22:13",
      "airport_intl": "22:14",
      "air_cargo": "22:16",
      "minami_chitose": "22:17",
      "asahi7": "22:20",
      "asahi4": "22:21",
      "city_hall": "22:22",
      "koizumi_clinic": "22:23",
      "mori_moto": "22:24",
      "chitose_st": "22:30",
      "hokuyou_hs": "22:38",
      "osatsu_st": "22:52"
    }
  }
];
